name: Postgresml extensions
on:
  workflow_dispatch: {}
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Agent readiness
        run: |
          set -xe
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /opt/hostedtoolcache/
          sudo rm -rf /usr/local/graalvm/
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/lib/node_modules
          sudo docker image prune --all --force
          
          APT_PARAMS='sudo apt -y -qq -o=Dpkg::Use-Pty=0'
          $APT_PARAMS remove -y '^dotnet-.*'
          $APT_PARAMS remove -y '^llvm-.*'
          $APT_PARAMS remove -y '^php.*'
          $APT_PARAMS remove -y '^mongodb-.*'
          $APT_PARAMS remove -y '^mysql-.*'
          $APT_PARAMS remove -y azure-cli google-* google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
          $APT_PARAMS autoremove --purge -y
          $APT_PARAMS autoclean
          $APT_PARAMS clean

      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Images
        run: |
          export CURRENT_BRANCH=${GITHUB_REF#refs/heads/}
          export TAG=`date +"%d-%m-%Y-%H-%M"`
          export GITHUB_REF_IMAGE=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
          export GITHUB_BRANCH_IMAGE=ghcr.io/$GITHUB_REPOSITORY:${TAG}
          export GITHUB_BRANCH_IMAGE=`echo "$GITHUB_BRANCH_IMAGE" | tr '[:upper:]' '[:lower:]'`
          docker build -t $GITHUB_BRANCH_IMAGE .
          echo "Pushing Image to GitHub Container Registry"
          docker push $GITHUB_BRANCH_IMAGE